import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/theme/theme-provider";
import Nav from "@/components/layout/navbar/nav";


export const metadata: Metadata = {
  title: "Ankit Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
      <body>
        <Provider>
          <Nav />
          {children}
        </Provider>
      </body>
    </html>
  );
}
